services:
  ms-solicitudes:
    build: .
    container_name: ms-solicitudes
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:3306/mesatech_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}