# spring.application.name=bff-service

server:
  port: 8082
spring:
  application:
    name: bff-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/TU-TENANT-ID/
