# spring.application.name=bff-service

server:
  port: 8082
spring:
  application:
    name: bff-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/6c5abb9a-09e5-470d-9973-e54cf9ad6475/v2.0
